---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qfpuksur/public_html/breconsulting
    - /bin/cp -R old $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH