---
deployment:
  tasks:
    - export DEPLOYPATH=/home/qfpuksur/public_html/breconsulting
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R sections $DEPLOYPATH
    - /bin/cp -R second $DEPLOYPATH
    - /bin/cp *.* $DEPLOYPATH
    